// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2U2LL4kdSYd1clW4iQSXr4PFKuK_1uaA',
    appId: '1:290068007404:web:1d83c9414eedd7063cd8c9',
    messagingSenderId: '290068007404',
    projectId: 'comfyspace-73966',
    authDomain: 'comfyspace-73966.firebaseapp.com',
    databaseURL: 'https://comfyspace-73966-default-rtdb.firebaseio.com',
    storageBucket: 'comfyspace-73966.appspot.com',
    measurementId: 'G-2K0LXM2NRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG9NIi1CqHf04jS7ZsT97xJ6Z-xEKQC0A',
    appId: '1:290068007404:android:81f97e93a31dc18c3cd8c9',
    messagingSenderId: '290068007404',
    projectId: 'comfyspace-73966',
    databaseURL: 'https://comfyspace-73966-default-rtdb.firebaseio.com',
    storageBucket: 'comfyspace-73966.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy_w8zYhIOejR_BrWW7Tejx_F8eSHRAjo',
    appId: '1:290068007404:ios:5cc79d18f5c2a18f3cd8c9',
    messagingSenderId: '290068007404',
    projectId: 'comfyspace-73966',
    databaseURL: 'https://comfyspace-73966-default-rtdb.firebaseio.com',
    storageBucket: 'comfyspace-73966.appspot.com',
    androidClientId: '290068007404-2p7fbvc66okoni2cvjnfnk57r3up8hdq.apps.googleusercontent.com',
    iosClientId: '290068007404-dddaof6j3r7br0340br9sft0gm7famvr.apps.googleusercontent.com',
    iosBundleId: 'com.example.bentoArena',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy_w8zYhIOejR_BrWW7Tejx_F8eSHRAjo',
    appId: '1:290068007404:ios:5cc79d18f5c2a18f3cd8c9',
    messagingSenderId: '290068007404',
    projectId: 'comfyspace-73966',
    databaseURL: 'https://comfyspace-73966-default-rtdb.firebaseio.com',
    storageBucket: 'comfyspace-73966.appspot.com',
    androidClientId: '290068007404-2p7fbvc66okoni2cvjnfnk57r3up8hdq.apps.googleusercontent.com',
    iosClientId: '290068007404-dddaof6j3r7br0340br9sft0gm7famvr.apps.googleusercontent.com',
    iosBundleId: 'com.example.bentoArena',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwA_sGw2llj4-EsTiWnX-uyRcTY62V1BA',
    appId: '1:290068007404:web:245d2347439be9093cd8c9',
    messagingSenderId: '290068007404',
    projectId: 'comfyspace-73966',
    authDomain: 'comfyspace-73966.firebaseapp.com',
    databaseURL: 'https://comfyspace-73966-default-rtdb.firebaseio.com',
    storageBucket: 'comfyspace-73966.appspot.com',
    measurementId: 'G-GPMTL08R27',
  );

}